from django.urls import path

from api.v1.restaurant.views import (
    CategoryDetailView,
    CategoryListCreateView,
    FloorDetailView,
    FloorListCreateView,
    IngredientDetailView,
    IngredientListCreateView,
    ItemDetailView,
    ItemListCreateView,
    ModifierDetailView,
    ModifierGroupDetailView,
    ModifierGroupListCreateView,
    ModifierListCreateView,
    OrderCancelView,
    OrderAddLineView,
    OrderDetailView,
    OrderListCreateView,
    OrderPosPayloadView,
    RecipeDetailView,
    RecipeIngredientCreateView,
    RecipeListCreateView,
    OrderRefundView,
    OrderSubmitView,
    OrderStatusView,
    OrderVoidView,
    RestaurantSummaryView,
    StationDetailView,
    StationListCreateView,
    TableDetailView,
    TableListCreateView,
    TableStatusView,
)
from api.v1.restaurant.cafeteria_views import (
    BaristaListCreateView,
    BaristaQueueView,
    BaristaTicketActionView,
    CafeteriaProfileView,
    ItemCustomizeByProductView,
    ItemVariantListCreateView,
    RecipeActivateView,
    RecipeCostingView,
    WasteApproveView,
    WasteListCreateView,
)
from api.v1.restaurant.commerce_views import (
    ComboDetailView,
    ComboListCreateView,
    ItemModifierGroupLinkView,
    LoyaltyEnrollView,
    LoyaltyProgramView,
    PromotionDetailView,
    PromotionListCreateView,
    PromotionResolveView,
    ReservationListCreateView,
    ReservationStatusView,
    ShiftActionView,
    ShiftListCreateView,
)

urlpatterns = [
    path("summary/", RestaurantSummaryView.as_view(), name="restaurant-summary"),
    path("categories/", CategoryListCreateView.as_view(), name="restaurant-categories"),
    path("categories/<uuid:pk>/", CategoryDetailView.as_view(), name="restaurant-category-detail"),
    path("items/", ItemListCreateView.as_view(), name="restaurant-items"),
    path("items/<uuid:pk>/", ItemDetailView.as_view(), name="restaurant-item-detail"),
    path("tables/", TableListCreateView.as_view(), name="restaurant-tables"),
    path("tables/<uuid:pk>/", TableDetailView.as_view(), name="restaurant-table-detail"),
    path("tables/<uuid:pk>/status/", TableStatusView.as_view(), name="restaurant-table-status"),
    path("floors/", FloorListCreateView.as_view(), name="restaurant-floors"),
    path("floors/<uuid:pk>/", FloorDetailView.as_view(), name="restaurant-floor-detail"),
    path("stations/", StationListCreateView.as_view(), name="restaurant-stations"),
    path("stations/<uuid:pk>/", StationDetailView.as_view(), name="restaurant-station-detail"),
    path("modifier-groups/", ModifierGroupListCreateView.as_view(), name="restaurant-modifier-groups"),
    path("modifier-groups/<uuid:pk>/", ModifierGroupDetailView.as_view(), name="restaurant-modifier-group-detail"),
    path("modifiers/", ModifierListCreateView.as_view(), name="restaurant-modifiers"),
    path("modifiers/<uuid:pk>/", ModifierDetailView.as_view(), name="restaurant-modifier-detail"),
    path("ingredients/", IngredientListCreateView.as_view(), name="restaurant-ingredients"),
    path("ingredients/<uuid:pk>/", IngredientDetailView.as_view(), name="restaurant-ingredient-detail"),
    path("recipes/", RecipeListCreateView.as_view(), name="restaurant-recipes"),
    path("recipes/<uuid:pk>/", RecipeDetailView.as_view(), name="restaurant-recipe-detail"),
    path("recipes/<uuid:pk>/ingredients/", RecipeIngredientCreateView.as_view(), name="restaurant-recipe-ingredients"),
    path("orders/", OrderListCreateView.as_view(), name="restaurant-orders"),
    path("orders/<uuid:pk>/", OrderDetailView.as_view(), name="restaurant-order-detail"),
    path("orders/<uuid:pk>/pos/", OrderPosPayloadView.as_view(), name="restaurant-order-pos"),
    path("orders/<uuid:pk>/status/", OrderStatusView.as_view(), name="restaurant-order-status"),
    path("orders/<uuid:pk>/submit/", OrderSubmitView.as_view(), name="restaurant-order-submit"),
    path("orders/<uuid:pk>/cancel/", OrderCancelView.as_view(), name="restaurant-order-cancel"),
    path("orders/<uuid:pk>/void/", OrderVoidView.as_view(), name="restaurant-order-void"),
    path("orders/<uuid:pk>/refund/", OrderRefundView.as_view(), name="restaurant-order-refund"),
    path("orders/<uuid:pk>/lines/", OrderAddLineView.as_view(), name="restaurant-order-lines"),
    # Cafeteria / barista extensions
    path("cafeteria-profile/", CafeteriaProfileView.as_view(), name="cafeteria-profile"),
    path("barista/queue/", BaristaQueueView.as_view(), name="barista-queue"),
    path(
        "barista/tickets/<uuid:pk>/<str:action>/",
        BaristaTicketActionView.as_view(),
        name="barista-ticket-action",
    ),
    path("waste/", WasteListCreateView.as_view(), name="restaurant-waste"),
    path("waste/<uuid:pk>/approve/", WasteApproveView.as_view(), name="restaurant-waste-approve"),
    path("baristas/", BaristaListCreateView.as_view(), name="restaurant-baristas"),
    path(
        "items/by-product/<uuid:product_id>/customize/",
        ItemCustomizeByProductView.as_view(),
        name="restaurant-item-customize-by-product",
    ),
    path(
        "items/<uuid:pk>/variants/",
        ItemVariantListCreateView.as_view(),
        name="restaurant-item-variants",
    ),
    path(
        "recipes/<uuid:pk>/activate/",
        RecipeActivateView.as_view(),
        name="restaurant-recipe-activate",
    ),
    path(
        "recipes/<uuid:pk>/costing/",
        RecipeCostingView.as_view(),
        name="restaurant-recipe-costing",
    ),
    path(
        "items/<uuid:pk>/modifier-groups/",
        ItemModifierGroupLinkView.as_view(),
        name="restaurant-item-modifier-groups",
    ),
    path("combos/", ComboListCreateView.as_view(), name="restaurant-combos"),
    path("combos/<uuid:pk>/", ComboDetailView.as_view(), name="restaurant-combo-detail"),
    path("promotions/", PromotionListCreateView.as_view(), name="restaurant-promotions"),
    path(
        "promotions/resolve/",
        PromotionResolveView.as_view(),
        name="restaurant-promotion-resolve",
    ),
    path(
        "promotions/<uuid:pk>/",
        PromotionDetailView.as_view(),
        name="restaurant-promotion-detail",
    ),
    path("loyalty/program/", LoyaltyProgramView.as_view(), name="restaurant-loyalty-program"),
    path("loyalty/enroll/", LoyaltyEnrollView.as_view(), name="restaurant-loyalty-enroll"),
    path("reservations/", ReservationListCreateView.as_view(), name="restaurant-reservations"),
    path(
        "reservations/<uuid:pk>/status/",
        ReservationStatusView.as_view(),
        name="restaurant-reservation-status",
    ),
    path("shifts/", ShiftListCreateView.as_view(), name="restaurant-shifts"),
    path(
        "shifts/<uuid:pk>/<str:action>/",
        ShiftActionView.as_view(),
        name="restaurant-shift-action",
    ),
]
