# Generated by Django 5.2.17 on 2026-08-07 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def backfill_futsal_tenants(apps, schema_editor):
    Tenant = apps.get_model("platform", "Tenant")
    legacy, _ = Tenant.objects.get_or_create(
        slug="legacy-unassigned",
        defaults={
            "name": "Legacy Unassigned",
            "status": "suspended",
            "is_active": False,
            "timezone": "UTC",
            "currency": "USD",
            "language": "en",
        },
    )
    models_to_fix = (
        "Court",
        "Team",
        "Player",
        "CourtBooking",
        "FutsalLedgerEntry",
    )
    for name in models_to_fix:
        Model = apps.get_model("futsal", name)
        for row in Model.objects.filter(tenant_id__isnull=True).select_related(
            "branch", "branch__company"
        ).iterator():
            branch = getattr(row, "branch", None)
            tenant_id = getattr(branch, "tenant_id", None) if branch is not None else None
            if not tenant_id and branch is not None:
                company = getattr(branch, "company", None)
                tenant_id = getattr(company, "tenant_id", None) if company is not None else None
            Model.objects.filter(pk=row.pk).update(tenant_id=tenant_id or legacy.id)


def noop_reverse(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_tenant_isolation"),
        ("futsal", "0001_initial"),
        ("platform", "0014_accounting_posting_enabled"),
        ("settings_app", "0003_tenant_isolation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="court",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="court",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="platform.tenant",
            ),
        ),
        migrations.AddField(
            model_name="courtbooking",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="platform.tenant",
            ),
        ),
        migrations.AddField(
            model_name="futsalledgerentry",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="platform.tenant",
            ),
        ),
        migrations.AddField(
            model_name="player",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="platform.tenant",
            ),
        ),
        migrations.AddField(
            model_name="team",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="%(app_label)s_%(class)s_set",
                to="platform.tenant",
            ),
        ),
        migrations.RunPython(backfill_futsal_tenants, noop_reverse),
        migrations.AddIndex(
            model_name="courtbooking",
            index=models.Index(
                fields=["tenant", "status", "start_at"], name="idx_futsal_booking_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="futsalledgerentry",
            index=models.Index(
                fields=["tenant", "entry_type", "entry_date"],
                name="idx_futsal_ledger_tenant",
            ),
        ),
        migrations.AddIndex(
            model_name="player",
            index=models.Index(
                fields=["tenant", "is_active", "full_name"], name="idx_futsal_player_tenant"
            ),
        ),
        migrations.AddIndex(
            model_name="team",
            index=models.Index(
                fields=["tenant", "is_active", "name"], name="idx_futsal_team_tenant"
            ),
        ),
        migrations.AddConstraint(
            model_name="court",
            constraint=models.UniqueConstraint(
                fields=("tenant", "branch", "code"),
                name="uniq_futsal_court_tenant_branch_code",
            ),
        ),
    ]
