# Generated by Django 5.2.17 on 2026-09-19 21:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_transfers'),
        ('organization', '0004_backfill_user_branch_access'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('products', '0007_product_module_code'),
        ('settings_app', '0005_branch_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorytransaction',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_transactions', to='organization.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text="Unused in Phase 3; reserved for Phase 4's transfer approval step.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_stock_movements', to='organization.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='destination_warehouse',
            field=models.ForeignKey(blank=True, help_text='Only meaningful for warehouse_move / branch_transfer_* movements.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incoming_stock_movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='organization.stocklocation'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='performed_by',
            field=models.ForeignKey(blank=True, help_text='The acting user, independent of BaseModel.created_by bookkeeping.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_stock_movements', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
        migrations.AlterField(
            model_name='inventorytransaction',
            name='transaction_type',
            field=models.CharField(choices=[('in', 'In'), ('out', 'Out'), ('reserve', 'Reserve'), ('unreserve', 'Unreserve'), ('damage', 'Damage'), ('return', 'Return'), ('write_off', 'Write Off')], db_index=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('adjustment', 'Adjustment'), ('purchase', 'Purchase'), ('purchase_return', 'Purchase Return'), ('sale', 'Sale'), ('transfer_in', 'Transfer In'), ('transfer_out', 'Transfer Out'), ('warehouse_move', 'Warehouse Move'), ('return', 'Return'), ('damage', 'Damage'), ('write_off', 'Write Off'), ('opening_balance', 'Opening Balance')], db_index=True, max_length=50),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'branch', 'product', 'created_at'], name='stock_movem_tenant__92b372_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['tenant', 'branch', 'movement_type'], name='stock_movem_tenant__f9b62d_idx'),
        ),
    ]
