# Generated by Django 5.2.17 on 2026-09-20 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_branch_transfer_workflow'),
    ]

    operations = [
        migrations.AddField(
            model_name='branchtransferline',
            name='unit_cost',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True),
        ),
    ]
