# Generated by Django 5.2.17 on 2026-09-11 21:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def prepare_existing(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name in ("SchoolProfile", "AcademicYear", "AcademicTerm"):
        model = apps.get_model("school", name)
        for row in model.objects.using(alias).select_related("branch__company").all():
            tenant_id = row.branch.tenant_id or row.branch.company.tenant_id
            if not tenant_id or (row.tenant_id and row.tenant_id != tenant_id):
                raise RuntimeError(f"School migration blocked: resolve tenant ownership for {name} {row.pk}.")
            row.tenant_id = tenant_id
            if name != "SchoolProfile":
                if row.start_date >= row.end_date:
                    raise RuntimeError(f"School migration blocked: correct date interval for {name} {row.pk}.")
                if not row.code:
                    row.code = ("AY-" if name == "AcademicYear" else "T-") + row.pk.hex[:16]
            if name == "AcademicTerm" and row.sort_order < 1:
                row.sort_order = 1
            if name == "AcademicYear" and row.is_current and (row.deleted_at or row.status != "active"):
                raise RuntimeError(f"School migration blocked: reconcile current year state for {row.pk}.")
            row.save(using=alias)
    Year = apps.get_model("school", "AcademicYear")
    from django.db.models import Count
    if Year.objects.using(alias).filter(is_current=True, deleted_at__isnull=True).values("tenant_id", "branch_id").annotate(n=Count("pk")).filter(n__gt=1).exists():
        raise RuntimeError("School migration blocked: select one current academic year per campus.")


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('school', '0001_initial'),
        ('settings_app', '0003_tenant_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolCampusAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SchoolClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('sequence', models.PositiveSmallIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('room', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SchoolShift',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('capacity', models.PositiveIntegerField(default=30)),
                ('room', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('short_name', models.CharField(blank=True, max_length=30)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('mandatory', models.BooleanField(default=True)),
                ('teaching_mode', models.CharField(choices=[('theory', 'Theory'), ('practical', 'Practical'), ('mixed', 'Mixed')], default='theory', max_length=16)),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectCategory',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubjectOffering',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=16)),
                ('description', models.TextField(blank=True)),
                ('maximum_marks', models.DecimalField(decimal_places=2, default=100, max_digits=8)),
                ('pass_mark', models.DecimalField(decimal_places=2, default=50, max_digits=8)),
                ('weight', models.DecimalField(decimal_places=2, default=1, max_digits=8)),
                ('weekly_periods', models.PositiveSmallIntegerField(default=1)),
                ('mandatory', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['name', 'id'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='academicterm',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='academicterm',
            name='result_publish_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='admission_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='code',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='academicyear',
            name='enrollment_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='allow_term_overlap',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='attendance_mode',
            field=models.CharField(choices=[('daily', 'Daily'), ('period', 'Period'), ('both', 'Both')], default='daily', max_length=16),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='authority_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='display_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='grading_scheme',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=16),
        ),
        migrations.AddField(
            model_name='schoolprofile',
            name='term_label',
            field=models.CharField(default='Term', max_length=30),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='status',
            field=models.CharField(choices=[('planning', 'Planning'), ('active', 'Active'), ('closed', 'Closed'), ('archived', 'Archived')], db_index=True, default='planning', max_length=20),
        ),
        migrations.RunPython(prepare_existing, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='school_term_dates'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('sort_order__gte', 1)), name='school_term_sequence'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant', 'academic_year', 'code'), name='school_term_code'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gt', models.F('start_date'))), name='school_year_dates'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('is_current', False), models.Q(('deleted_at__isnull', True), ('status', 'active')), _connector='OR'), name='school_year_current_state'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('code', ''), _negated=True), fields=('tenant', 'code'), name='school_year_code'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_current', True)), fields=('tenant', 'branch'), name='school_one_current_year'),
        ),
        migrations.AddConstraint(
            model_name='schoolprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('school_code', ''), _negated=True), fields=('tenant', 'school_code'), name='school_profile_code'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='educationlevel',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolcampusaccess',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='schoolcampusaccess',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolcampusaccess',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolcampusaccess',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='schoolcampusaccess',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolcampusaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='school_campus_access', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='education_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classes', to='school.educationlevel'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='schoolclass',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolshift',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='schoolshift',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolshift',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schoolshift',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='schoolshift',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='section',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sections', to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='section',
            name='shift',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.schoolshift'),
        ),
        migrations.AddField(
            model_name='section',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_sections', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='section',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='section',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='subject',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='subjectcategory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subject',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='school.subjectcategory'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='school.academicyear'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='school_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='school.schoolclass'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='school.section'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='school.subject'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='school_offerings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='term',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='offerings', to='school.academicterm'),
        ),
        migrations.AddField(
            model_name='subjectoffering',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='educationlevel',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='school_level_code'),
        ),
        migrations.AddConstraint(
            model_name='schoolcampusaccess',
            constraint=models.UniqueConstraint(fields=('tenant', 'user', 'branch'), name='school_campus_access_unique'),
        ),
        migrations.AddIndex(
            model_name='schoolclass',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='school_scho_tenant__41d876_idx'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'code'), name='school_class_code'),
        ),
        migrations.AddConstraint(
            model_name='schoolclass',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='school_class_capacity'),
        ),
        migrations.AddConstraint(
            model_name='schoolshift',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'code'), name='school_shift_code'),
        ),
        migrations.AddConstraint(
            model_name='schoolshift',
            constraint=models.CheckConstraint(condition=models.Q(('end_time__gt', models.F('start_time'))), name='school_shift_dates'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('tenant', 'school_class', 'code'), name='school_section_code'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.UniqueConstraint(fields=('tenant', 'school_class', 'name'), name='school_section_name'),
        ),
        migrations.AddConstraint(
            model_name='section',
            constraint=models.CheckConstraint(condition=models.Q(('capacity__gt', 0)), name='school_section_capacity'),
        ),
        migrations.AddConstraint(
            model_name='subjectcategory',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='school_subject_category_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('tenant', 'code'), name='school_subject_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_marks__gt', 0), ('pass_mark__gte', 0), ('pass_mark__lte', models.F('maximum_marks')), ('weight__gt', 0)), name='school_subject_marks'),
        ),
        migrations.AddIndex(
            model_name='subjectoffering',
            index=models.Index(fields=['tenant', 'branch', 'academic_year', 'status'], name='school_subj_tenant__2b5a84_idx'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(fields=('tenant', 'branch', 'code'), name='school_offering_code'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.CheckConstraint(condition=models.Q(('maximum_marks__gt', 0), ('pass_mark__gte', 0), ('pass_mark__lte', models.F('maximum_marks')), ('weekly_periods__gt', 0), ('weight__gt', 0)), name='school_offering_marks'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('section__isnull', True), ('status', 'active'), ('term__isnull', True)), fields=('tenant', 'academic_year', 'branch', 'school_class', 'subject'), name='school_offering_scope_00'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('section__isnull', False), ('status', 'active'), ('term__isnull', True)), fields=('tenant', 'academic_year', 'branch', 'school_class', 'subject', 'section'), name='school_offering_scope_01'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('section__isnull', True), ('status', 'active'), ('term__isnull', False)), fields=('tenant', 'academic_year', 'branch', 'school_class', 'subject', 'term'), name='school_offering_scope_10'),
        ),
        migrations.AddConstraint(
            model_name='subjectoffering',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('section__isnull', False), ('status', 'active'), ('term__isnull', False)), fields=('tenant', 'academic_year', 'branch', 'school_class', 'subject', 'term', 'section'), name='school_offering_scope_11'),
        ),
    ]
