# Generated by Django 5.2.17 on 2026-09-11 21:54

import django.db.models.deletion
from django.db import migrations, models


def fix_school_dependency(apps, schema_editor):
    for name, field, lookup in (("Module", "dependencies", {"code": "school"}), ("BusinessType", "default_modules", {"code": "school"})):
        model = apps.get_model("platform", name)
        for row in model.objects.using(schema_editor.connection.alias).filter(**lookup):
            setattr(row, field, [c for c in getattr(row, field) if c != "finance"])
            row.save(using=schema_editor.connection.alias, update_fields=[field])


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_foundation_fields'),
        ('settings_app', '0003_tenant_isolation'),
    ]

    operations = [
        migrations.RunPython(fix_school_dependency, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='academicterm',
            name='academic_year',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='terms', to='school.academicyear'),
        ),
        migrations.AlterField(
            model_name='academicterm',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_academic_terms', to='settings_app.branch'),
        ),
        migrations.AlterField(
            model_name='academicyear',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_academic_years', to='settings_app.branch'),
        ),
        migrations.AlterField(
            model_name='schoolprofile',
            name='branch',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='school_profile', to='settings_app.branch'),
        ),
    ]
