# Generated by Django 5.2.17 on 2026-09-11 22:06

from django.conf import settings
from django.db import migrations, models


def validate_legacy_relationships(apps, schema_editor):
    alias = schema_editor.connection.alias
    for name in ("AcademicYear", "AcademicTerm", "SchoolProfile"):
        model = apps.get_model("school", name)
        for row in model.objects.using(alias).select_related("branch__company"):
            if row.branch.tenant_id != row.tenant_id or row.branch.company.tenant_id != row.tenant_id:
                raise RuntimeError(f"School migration blocked: resolve campus/company tenant for {name} {row.pk}.")
            if name == "AcademicTerm":
                year = row.academic_year
                if year.tenant_id != row.tenant_id or year.branch_id != row.branch_id or row.start_date < year.start_date or row.end_date > year.end_date:
                    raise RuntimeError(f"School migration blocked: resolve term/year relationship for {row.pk}.")
            if name == "SchoolProfile" and row.principal_user_id and row.principal_user.tenant_id != row.tenant_id:
                raise RuntimeError(f"School migration blocked: resolve cross-tenant principal for {row.pk}.")


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('school', '0003_protect_academic_history'),
        ('settings_app', '0004_foundation_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(validate_legacy_relationships, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='academicterm',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', False)), name='academicterm_tenant_required'),
        ),
        migrations.AddConstraint(
            model_name='academicterm',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planning', 'active', 'closed', 'archived'])), name='academicterm_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', False)), name='academicyear_tenant_required'),
        ),
        migrations.AddConstraint(
            model_name='academicyear',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['planning', 'active', 'closed', 'archived'])), name='academicyear_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='schoolprofile',
            constraint=models.CheckConstraint(condition=models.Q(('tenant__isnull', False)), name='school_profile_tenant_required'),
        ),
    ]
