# Generated by Django 5.2.17 on 2026-09-21 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_phase5'),
    ]

    operations = [
        migrations.AddField(
            model_name='gradescheme',
            name='ranking',
            field=models.CharField(choices=[('none', 'None'), ('competition', 'Competition'), ('dense', 'Dense')], default='none', max_length=20),
        ),
    ]
