# Generated by Django 5.2.17 on 2026-08-11 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_management', '0008_materialrequest_purchase_order_and_more'),
        ('purchases', '0002_tenant_isolation'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='project_management.project'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='wbs_node',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='project_management.wbsnode'),
        ),
    ]
