# Generated by Django 5.2.17 on 2026-08-07 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('gym_membership_expiry', 'Gym membership expiry'), ('pharmacy_batch_expiry', 'Pharmacy batch expiry'), ('accounting_health', 'Accounting health'), ('system', 'System')], db_index=True, max_length=50),
        ),
    ]
