# Generated by Django 5.2.17 on 2026-09-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_accounting_health_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('gym_membership_expiry', 'Gym membership expiry'), ('pharmacy_batch_expiry', 'Pharmacy batch expiry'), ('accounting_health', 'Accounting health'), ('system', 'System'), ('branch_transfer', 'Branch transfer')], db_index=True, max_length=50),
        ),
    ]
