# Generated by Django 5.2.17 on 2026-09-20 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        ('settings_app', '0005_branch_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='action_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='notification',
            name='audience',
            field=models.CharField(choices=[('USER', 'Single user'), ('BRANCH', 'Branch staff'), ('BRANCH_MANAGERS', 'Branch managers'), ('TENANT', 'Whole tenant')], default='USER', max_length=20),
        ),
        migrations.AddField(
            model_name='notification',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='notification',
            name='entity_type',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='notification',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='severity',
            field=models.CharField(choices=[('INFO', 'Info'), ('WARNING', 'Warning'), ('CRITICAL', 'Critical')], db_index=True, default='INFO', max_length=10),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('low_stock', 'Low stock'), ('gym_membership_expiry', 'Gym membership expiry'), ('pharmacy_batch_expiry', 'Pharmacy batch expiry'), ('accounting_health', 'Accounting health'), ('system', 'System'), ('branch_transfer', 'Branch transfer'), ('cash_variance', 'Cash variance')], db_index=True, max_length=50),
        ),
    ]
