from django.urls import path

from api.v1.gym.views import (
    AssignmentEndView,
    AssignmentListCreateView,
    AttendanceCheckInView,
    AttendanceCheckOutView,
    AttendanceListView,
    BodyMeasurementChartView,
    BodyMeasurementListCreateView,
    ClassBookingCancelView,
    ClassBookingCheckoutView,
    ClassBookingListCreateView,
    ClassScheduleListCreateView,
    ExerciseListCreateView,
    GymClassListCreateView,
    GymCheckoutView,
    GymSummaryView,
    MemberDetailView,
    MemberListCreateView,
    PlanDetailView,
    PlanListCreateView,
    PTSessionCheckoutView,
    PTSessionListCreateView,
    PTSessionStatusView,
    SubscriptionActivateView,
    SubscriptionCancelView,
    SubscriptionDetailView,
    SubscriptionFreezeView,
    SubscriptionListCreateView,
    SubscriptionPayView,
    SubscriptionUnfreezeView,
    TrainerDetailView,
    TrainerListCreateView,
    WorkoutAssignmentListCreateView,
    WorkoutPlanDetailView,
    WorkoutPlanListCreateView,
    WorkoutProgressListCreateView,
)

urlpatterns = [
    path("summary/", GymSummaryView.as_view(), name="gym-summary"),
    path("members/", MemberListCreateView.as_view(), name="gym-members"),
    path("members/<uuid:pk>/", MemberDetailView.as_view(), name="gym-member-detail"),
    path("plans/", PlanListCreateView.as_view(), name="gym-plans"),
    path("plans/<uuid:pk>/", PlanDetailView.as_view(), name="gym-plan-detail"),
    path("subscriptions/", SubscriptionListCreateView.as_view(), name="gym-subscriptions"),
    path(
        "subscriptions/<uuid:pk>/",
        SubscriptionDetailView.as_view(),
        name="gym-subscription-detail",
    ),
    path(
        "subscriptions/<uuid:pk>/activate/",
        SubscriptionActivateView.as_view(),
        name="gym-subscription-activate",
    ),
    path(
        "subscriptions/<uuid:pk>/freeze/",
        SubscriptionFreezeView.as_view(),
        name="gym-subscription-freeze",
    ),
    path(
        "subscriptions/<uuid:pk>/unfreeze/",
        SubscriptionUnfreezeView.as_view(),
        name="gym-subscription-unfreeze",
    ),
    path(
        "subscriptions/<uuid:pk>/pay/",
        SubscriptionPayView.as_view(),
        name="gym-subscription-pay",
    ),
    path(
        "subscriptions/<uuid:pk>/cancel/",
        SubscriptionCancelView.as_view(),
        name="gym-subscription-cancel",
    ),
    path("checkout/", GymCheckoutView.as_view(), name="gym-checkout"),
    path("attendance/", AttendanceListView.as_view(), name="gym-attendance"),
    path("attendance/check-in/", AttendanceCheckInView.as_view(), name="gym-attendance-checkin"),
    path(
        "attendance/check-out/", AttendanceCheckOutView.as_view(), name="gym-attendance-checkout"
    ),
    path("trainers/", TrainerListCreateView.as_view(), name="gym-trainers"),
    path("trainers/<uuid:pk>/", TrainerDetailView.as_view(), name="gym-trainer-detail"),
    path("assignments/", AssignmentListCreateView.as_view(), name="gym-assignments"),
    path(
        "assignments/<uuid:pk>/end/",
        AssignmentEndView.as_view(),
        name="gym-assignment-end",
    ),
    path("pt-sessions/", PTSessionListCreateView.as_view(), name="gym-pt-sessions"),
    path(
        "pt-sessions/<uuid:pk>/status/",
        PTSessionStatusView.as_view(),
        name="gym-pt-session-status",
    ),
    path(
        "pt-sessions/<uuid:pk>/checkout/",
        PTSessionCheckoutView.as_view(),
        name="gym-pt-session-checkout",
    ),
    path("classes/", GymClassListCreateView.as_view(), name="gym-classes"),
    path("class-schedules/", ClassScheduleListCreateView.as_view(), name="gym-class-schedules"),
    path("class-bookings/", ClassBookingListCreateView.as_view(), name="gym-class-bookings"),
    path(
        "class-bookings/<uuid:pk>/cancel/",
        ClassBookingCancelView.as_view(),
        name="gym-class-booking-cancel",
    ),
    path(
        "class-bookings/<uuid:pk>/checkout/",
        ClassBookingCheckoutView.as_view(),
        name="gym-class-booking-checkout",
    ),
    path("exercises/", ExerciseListCreateView.as_view(), name="gym-exercises"),
    path("workout-plans/", WorkoutPlanListCreateView.as_view(), name="gym-workout-plans"),
    path(
        "workout-plans/<uuid:pk>/",
        WorkoutPlanDetailView.as_view(),
        name="gym-workout-plan-detail",
    ),
    path(
        "workout-assignments/",
        WorkoutAssignmentListCreateView.as_view(),
        name="gym-workout-assignments",
    ),
    path(
        "workout-progress/",
        WorkoutProgressListCreateView.as_view(),
        name="gym-workout-progress",
    ),
    path(
        "body-measurements/",
        BodyMeasurementListCreateView.as_view(),
        name="gym-body-measurements",
    ),
    path(
        "body-measurements/chart/",
        BodyMeasurementChartView.as_view(),
        name="gym-body-measurements-chart",
    ),
]
