# Generated by Django 5.2.17 on 2026-08-07 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0012_sync_outbox_ingest'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='accounting_cutover_date',
            field=models.DateField(blank=True, db_index=True, help_text='Ledger-authoritative from this date; earlier docs may be backfilled.', null=True),
        ),
    ]
