# Generated by Django 5.2.17 on 2026-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0013_accounting_cutover_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenantsettings',
            name='accounting_posting_enabled',
            field=models.BooleanField(db_index=True, default=True, help_text='When False, CAE posting is skipped for this tenant (pilot rollback).'),
        ),
    ]
