# Generated by Django 5.2.17 on 2026-08-07 13:12

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0014_accounting_posting_enabled'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='dashboard_route',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='icon',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='module',
            name='is_core',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='optional_dependencies',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='module',
            name='route',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='module',
            name='supports_finance',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='module',
            name='supports_inventory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='supports_mobile',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='module',
            name='supports_pos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='configuration',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='disabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='disabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_modules_disabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='enabled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tenantmodule',
            name='enabled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tenant_modules_enabled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='BusinessPreset',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('icon', models.CharField(blank=True, default='', max_length=50)),
                ('version', models.PositiveSmallIntegerField(default=1)),
                ('is_system', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveSmallIntegerField(default=100)),
                ('business_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presets', to='platform.businesstype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_presets',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BusinessPresetModule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_required', models.BooleanField(default=False)),
                ('is_default', models.BooleanField(default=True)),
                ('display_order', models.PositiveSmallIntegerField(default=100)),
                ('default_configuration', models.JSONField(blank=True, default=dict)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_links', to='platform.module')),
                ('preset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preset_modules', to='platform.businesspreset')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'business_preset_modules',
                'ordering': ['display_order', 'module__code'],
                'constraints': [models.UniqueConstraint(fields=('preset', 'module'), name='uniq_business_preset_module')],
            },
        ),
    ]
