# Generated by Django 5.2.17 on 2026-09-23 14:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0003_sms_billing'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('sales', '0012_phase6_adjustment_reversals'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='currency',
            field=models.CharField(blank=True, max_length=3),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='intent',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subscription_payment', to='integrations.paymentintent'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='kind',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='platform.subscriptionplan'),
        ),
        migrations.AlterField(
            model_name='subscriptionpayment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('failed', 'Failed'), ('expired', 'Expired'), ('review', 'Under review')], db_index=True, default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='subscriptionpayment',
            constraint=models.UniqueConstraint(condition=models.Q(('idempotency_key', ''), _negated=True), fields=('subscription', 'idempotency_key'), name='uniq_subscription_payment_key'),
        ),
    ]
