# Generated by Django 5.2.13 on 2026-06-17 15:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("platform", "0001_platform_cloud"),
        ("settings_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="tenant",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="companies",
                to="platform.tenant",
            ),
        ),
    ]
