# Generated by Django 5.2.17 on 2026-09-11 22:06

from django.conf import settings
from django.db import migrations, models


def check_codes(apps, schema_editor):
    from django.db.models import Count
    Branch = apps.get_model("settings_app", "Branch")
    duplicates = Branch.objects.using(schema_editor.connection.alias).exclude(tenant_id=None).values("tenant_id", "code").annotate(n=Count("pk")).filter(n__gt=1)
    if duplicates.exists():
        raise RuntimeError("Campus migration blocked: reconcile duplicate Branch codes within each tenant before retrying.")


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('settings_app', '0003_tenant_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(check_codes, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='branch',
            constraint=models.UniqueConstraint(condition=models.Q(('tenant__isnull', False)), fields=('tenant', 'code'), name='branch_tenant_code_unique'),
        ),
    ]
