# Generated by Django 5.2.17 on 2026-09-19 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('settings_app', '0004_foundation_integrity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='branch_type',
            field=models.CharField(choices=[('RETAIL', 'Retail Branch'), ('WAREHOUSE', 'Warehouse / Depot'), ('OUTLET', 'Outlet'), ('HEAD_OFFICE', 'Head Office'), ('CAMPUS', 'Campus'), ('OTHER', 'Other')], db_default='RETAIL', default='RETAIL', max_length=20),
        ),
        migrations.AddField(
            model_name='branch',
            name='city',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
        migrations.AddField(
            model_name='branch',
            name='country',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
        migrations.AddField(
            model_name='branch',
            name='currency',
            field=models.CharField(blank=True, db_default='', max_length=8),
        ),
        migrations.AddField(
            model_name='branch',
            name='invoice_prefix',
            field=models.CharField(blank=True, db_default='', max_length=16),
        ),
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='legal_name',
            field=models.CharField(blank=True, db_default='', max_length=255),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_branches', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='branch',
            name='notes',
            field=models.TextField(blank=True, db_default=''),
        ),
        migrations.AddField(
            model_name='branch',
            name='opening_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='branch',
            name='order_prefix',
            field=models.CharField(blank=True, db_default='', max_length=16),
        ),
        migrations.AddField(
            model_name='branch',
            name='receipt_prefix',
            field=models.CharField(blank=True, db_default='', max_length=16),
        ),
        migrations.AddField(
            model_name='branch',
            name='region',
            field=models.CharField(blank=True, db_default='', max_length=120),
        ),
        migrations.AddField(
            model_name='branch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('TEMPORARILY_CLOSED', 'Temporarily Closed'), ('ARCHIVED', 'Archived')], db_default='ACTIVE', db_index=True, default='ACTIVE', max_length=24),
        ),
        migrations.AddField(
            model_name='branch',
            name='timezone',
            field=models.CharField(blank=True, db_default='', max_length=64),
        ),
        migrations.AddField(
            model_name='branch',
            name='transfer_prefix',
            field=models.CharField(blank=True, db_default='', max_length=16),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['tenant', 'status'], name='branch_tenant_status_idx'),
        ),
        migrations.AddIndex(
            model_name='branch',
            index=models.Index(fields=['company', 'is_active'], name='branch_company_active_idx'),
        ),
    ]
