"""Standard accounting event types for the Central Accounting Engine."""

SALE_COMPLETED = "SALE_COMPLETED"
SALE_REFUNDED = "SALE_REFUNDED"
SALE_VOIDED = "SALE_VOIDED"
CUSTOMER_INVOICE_POSTED = "CUSTOMER_INVOICE_POSTED"
CUSTOMER_PAYMENT_RECEIVED = "CUSTOMER_PAYMENT_RECEIVED"
PROJECT_INVOICE_ISSUED = "PROJECT_INVOICE_ISSUED"
TRAVEL_BOOKING_CONFIRMED = "TRAVEL_BOOKING_CONFIRMED"
TRAVEL_COMMISSION_APPROVED = "TRAVEL_COMMISSION_APPROVED"
TRAVEL_PAYMENT_RECEIVED = "TRAVEL_PAYMENT_RECEIVED"
TRAVEL_REFUND_ISSUED = "TRAVEL_REFUND_ISSUED"

PURCHASE_RECEIVED = "PURCHASE_RECEIVED"
SUPPLIER_BILL_POSTED = "SUPPLIER_BILL_POSTED"
SUPPLIER_PAYMENT_COMPLETED = "SUPPLIER_PAYMENT_COMPLETED"

EXPENSE_APPROVED = "EXPENSE_APPROVED"
EXPENSE_PAID = "EXPENSE_PAID"

TRANSFER_DISPATCHED = "TRANSFER_DISPATCHED"
TRANSFER_RECEIVED = "TRANSFER_RECEIVED"

INVENTORY_ADJUSTED = "INVENTORY_ADJUSTED"
INVENTORY_WRITTEN_OFF = "INVENTORY_WRITTEN_OFF"

GYM_MEMBERSHIP_SOLD = "GYM_MEMBERSHIP_SOLD"
GYM_SERVICE_SOLD = "GYM_SERVICE_SOLD"

PHARMACY_SALE_COMPLETED = "PHARMACY_SALE_COMPLETED"
RESTAURANT_ORDER_PAID = "RESTAURANT_ORDER_PAID"
CAFETERIA_WASTE_POSTED = "CAFETERIA_WASTE_POSTED"
CAFETERIA_TIP_RECORDED = "CAFETERIA_TIP_RECORDED"
CAFETERIA_SERVICE_CHARGE = "CAFETERIA_SERVICE_CHARGE"

HOTEL_ROOM_CHARGED = "HOTEL_ROOM_CHARGED"
HOTEL_SERVICE_CHARGED = "HOTEL_SERVICE_CHARGED"

FUTSAL_INCOME_RECORDED = "FUTSAL_INCOME_RECORDED"
FUTSAL_EXPENSE_RECORDED = "FUTSAL_EXPENSE_RECORDED"

BANK_TRANSFER_COMPLETED = "BANK_TRANSFER_COMPLETED"
RECEIPT_VOUCHER_POSTED = "RECEIPT_VOUCHER_POSTED"
PAYMENT_VOUCHER_POSTED = "PAYMENT_VOUCHER_POSTED"
JOURNAL_VOUCHER_POSTED = "JOURNAL_VOUCHER_POSTED"

CREDIT_NOTE_POSTED = "CREDIT_NOTE_POSTED"
DEBIT_NOTE_POSTED = "DEBIT_NOTE_POSTED"

ALL_EVENT_TYPES = frozenset(
    {
        SALE_COMPLETED,
        SALE_REFUNDED,
        SALE_VOIDED,
        CUSTOMER_INVOICE_POSTED,
        CUSTOMER_PAYMENT_RECEIVED,
        PROJECT_INVOICE_ISSUED,
        TRAVEL_BOOKING_CONFIRMED,
        TRAVEL_COMMISSION_APPROVED,
        TRAVEL_PAYMENT_RECEIVED,
        TRAVEL_REFUND_ISSUED,
        PURCHASE_RECEIVED,
        SUPPLIER_BILL_POSTED,
        SUPPLIER_PAYMENT_COMPLETED,
        EXPENSE_APPROVED,
        EXPENSE_PAID,
        TRANSFER_DISPATCHED,
        TRANSFER_RECEIVED,
        INVENTORY_ADJUSTED,
        INVENTORY_WRITTEN_OFF,
        GYM_MEMBERSHIP_SOLD,
        GYM_SERVICE_SOLD,
        PHARMACY_SALE_COMPLETED,
        RESTAURANT_ORDER_PAID,
        CAFETERIA_WASTE_POSTED,
        CAFETERIA_TIP_RECORDED,
        CAFETERIA_SERVICE_CHARGE,
        HOTEL_ROOM_CHARGED,
        HOTEL_SERVICE_CHARGED,
        FUTSAL_INCOME_RECORDED,
        FUTSAL_EXPENSE_RECORDED,
        BANK_TRANSFER_COMPLETED,
        RECEIPT_VOUCHER_POSTED,
        PAYMENT_VOUCHER_POSTED,
        JOURNAL_VOUCHER_POSTED,
        CREDIT_NOTE_POSTED,
        DEBIT_NOTE_POSTED,
    }
)

# School Phase 6 shared billing events.
SCHOOL_BILLING_EVENTS = frozenset({"SCHOOL_FEE_INVOICED", "SCHOOL_FEE_PAYMENT", "SCHOOL_FEE_ALLOCATED", "SCHOOL_FEE_CREDIT", "SCHOOL_FEE_REFUND"})
ALL_EVENT_TYPES = ALL_EVENT_TYPES | SCHOOL_BILLING_EVENTS
