# Generated by Django 5.2.17 on 2026-08-11 10:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_tenant_isolation'),
        ('finance', '0009_business_units'),
        ('platform', '0016_demo_tenant_fields'),
        ('settings_app', '0003_tenant_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('project_code', models.CharField(db_index=True, max_length=40)),
                ('name', models.CharField(db_index=True, max_length=200)),
                ('project_type', models.CharField(choices=[('general', 'General'), ('construction', 'Construction'), ('real_estate', 'Real Estate Development'), ('infrastructure', 'Infrastructure'), ('it', 'IT'), ('professional', 'Professional Services')], db_index=True, default='general', max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=120)),
                ('location', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('planned_end_date', models.DateField(blank=True, null=True)),
                ('actual_end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('planning', 'Planning'), ('approved', 'Approved'), ('active', 'Active'), ('on_hold', 'On Hold'), ('at_risk', 'At Risk'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('closed', 'Closed')], db_index=True, default='draft', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], db_index=True, default='medium', max_length=20)),
                ('health', models.CharField(choices=[('on_track', 'On Track'), ('at_risk', 'At Risk'), ('critical', 'Critical'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=20)),
                ('progress_percent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('budget', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('contract_value', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('expected_revenue', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('cost_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('profit_estimate', models.DecimalField(decimal_places=2, default=0, max_digits=16)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('tax_rate', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('payment_terms', models.CharField(blank=True, max_length=120)),
                ('notes', models.TextField(blank=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='settings_app.branch')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='customers.customer')),
                ('cost_center', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='finance.costcenter')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('project_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_projects', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'project_management_projects',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status', 'project_type'], name='idx_proj_tenant_status')],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'branch', 'project_code'), name='uniq_proj_tenant_branch_code')],
            },
        ),
    ]
