# Generated by Django 5.2.17 on 2026-08-11 11:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_business_units'),
        ('project_management', '0006_materialrequest_materialrequestline_projectequipment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinvoice',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='project_invoices', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='projectinvoice',
            name='posted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
