# Generated by Django 5.2.17 on 2026-09-19 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('audit', '0003_tenant_isolation'),
        ('settings_app', '0004_foundation_integrity'),
    ]

    operations = [
        migrations.AddField(
            model_name='auditlog',
            name='branch',
            field=models.ForeignKey(blank=True, help_text='Branch the mutation happened in. Forward-only: historical rows keep NULL because back-dating a branch onto an audit row would falsify the trail.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='settings_app.branch'),
        ),
    ]
