# Generated by Django 5.2.17 on 2026-08-07 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_bank_reconciliation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('expense', 'Expense'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('refund', 'Refund'), ('purchase', 'Purchase'), ('futsal', 'Futsal')], db_index=True, default='manual', max_length=20),
        ),
    ]
