# Generated by Django 5.2.17 on 2026-09-20 05:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_business_units'),
        ('settings_app', '0005_branch_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalline',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='journal_lines', to='settings_app.branch'),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_type',
            field=models.CharField(choices=[('manual', 'Manual'), ('expense', 'Expense'), ('payment', 'Payment'), ('invoice', 'Invoice'), ('refund', 'Refund'), ('purchase', 'Purchase'), ('futsal', 'Futsal'), ('transfer', 'Inter-branch transfer')], db_index=True, default='manual', max_length=20),
        ),
    ]
