# Generated by Django 5.2.13 on 2026-06-23 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0004_staff_evaluations"),
        ("platform", "0005_shop_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="managed_shop_group",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="managers",
                to="platform.shopgroup",
            ),
        ),
    ]
