export type RootStackParamList = {
  WorkspaceSwitcher: undefined;
  DashboardWorkspace: undefined;
  PosWorkspace: undefined;
  SalesWorkspace: undefined;
  InventoryWorkspace: undefined;
  PurchasesWorkspace: undefined;
  CustomersWorkspace: undefined;
  SuppliersWorkspace: undefined;
  FinanceWorkspace: undefined;
  BusinessUnitsWorkspace: undefined;
  ReportsWorkspace: undefined;
  SettingsWorkspace: undefined;
  GymWorkspace: undefined;
  PharmacyWorkspace: undefined;
  HotelWorkspace: undefined;
  RestaurantWorkspace: undefined;
  PropertyWorkspace: undefined;
  HousingWorkspace: undefined;
  OfficeWorkspace: undefined;
  FutsalWorkspace: undefined;
};
