# Generated by Django 5.2.17 on 2026-09-06 12:04

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_stock_transfers'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('products', '0007_product_module_code'),
        ('restaurant', '0003_restaurant_masters_modifiers_recipes'),
        ('settings_app', '0003_tenant_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BaristaProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('barista_code', models.CharField(blank=True, db_index=True, max_length=40)),
                ('skill_level', models.CharField(choices=[('trainee', 'Trainee'), ('junior', 'Junior barista'), ('barista', 'Barista'), ('senior', 'Senior barista'), ('lead', 'Lead barista'), ('supervisor', 'Supervisor')], default='barista', max_length=20)),
                ('specialization', models.CharField(blank=True, max_length=120)),
                ('employment_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('certification', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'restaurant_barista_profiles',
                'ordering': ['barista_code', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='CafeteriaProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('trading_name', models.CharField(blank=True, max_length=255)),
                ('logo_url', models.CharField(blank=True, max_length=500)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
                ('currency', models.CharField(default='USD', max_length=8)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('language', models.CharField(default='en', max_length=16)),
                ('receipt_header', models.TextField(blank=True)),
                ('receipt_footer', models.TextField(blank=True)),
                ('order_prefix', models.CharField(default='CF', max_length=20)),
                ('invoice_prefix', models.CharField(default='INV-CF', max_length=20)),
                ('kitchen_barista_mode', models.CharField(choices=[('both', 'Barista + Kitchen'), ('barista', 'Barista only'), ('kitchen', 'Kitchen only')], default='both', max_length=20)),
                ('table_service_enabled', models.BooleanField(default=True)),
                ('takeaway_enabled', models.BooleanField(default=True)),
                ('delivery_enabled', models.BooleanField(default=False)),
                ('reservations_enabled', models.BooleanField(default=False)),
                ('tips_enabled', models.BooleanField(default=True)),
                ('service_charge_enabled', models.BooleanField(default=False)),
                ('loyalty_enabled', models.BooleanField(default=False)),
                ('recipe_deduction_enabled', models.BooleanField(default=True)),
                ('negative_stock_allowed', models.BooleanField(default=False)),
                ('default_cash_account_id', models.UUIDField(blank=True, null=True)),
                ('default_sales_account_id', models.UUIDField(blank=True, null=True)),
                ('default_inventory_account_id', models.UUIDField(blank=True, null=True)),
                ('default_cogs_account_id', models.UUIDField(blank=True, null=True)),
                ('settings', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'db_table': 'restaurant_cafeteria_profiles',
                'ordering': ['business_name'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemModifierGroup',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'db_table': 'restaurant_menu_item_modifier_groups',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='MenuItemVariant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('sku', models.CharField(blank=True, db_index=True, max_length=50)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64)),
                ('price_adjustment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('recipe_qty_multiplier', models.DecimalField(decimal_places=3, default=1, max_digits=8)),
                ('is_default', models.BooleanField(default=False)),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('sort_order', models.PositiveIntegerField(default=100)),
            ],
            options={
                'db_table': 'restaurant_menu_item_variants',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='OrderLineModifier',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('price_delta', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('quantity', models.DecimalField(decimal_places=3, default=1, max_digits=12)),
            ],
            options={
                'db_table': 'restaurant_order_line_modifiers',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='WasteRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('waste_date', models.DateField(db_index=True, default=django.utils.timezone.localdate)),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12)),
                ('unit', models.CharField(default='unit', max_length=30)),
                ('unit_cost', models.DecimalField(decimal_places=4, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('waste_type', models.CharField(choices=[('expired', 'Expired'), ('spoiled', 'Spoiled'), ('prep', 'Prep loss'), ('spillage', 'Spillage'), ('burned', 'Burned'), ('damaged', 'Damaged'), ('employee_meal', 'Employee meal'), ('sample', 'Sample / tasting'), ('other', 'Other')], db_index=True, default='other', max_length=20)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('approval_status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='draft', max_length=20)),
                ('inventory_adjustment_id', models.UUIDField(blank=True, null=True)),
                ('photo_url', models.CharField(blank=True, max_length=500)),
            ],
            options={
                'db_table': 'restaurant_waste_records',
                'ordering': ['-waste_date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='ingredient',
            name='average_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='batch_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='consumption_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='conversion_rate',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='expiry_tracking',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='last_cost',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='max_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='min_stock',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='purchase_unit',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='reorder_level',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='storage_location',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='kitchenstation',
            name='station_type',
            field=models.CharField(choices=[('coffee_bar', 'Coffee bar'), ('cold_drinks', 'Cold drinks'), ('kitchen', 'Kitchen'), ('bakery', 'Bakery'), ('dessert', 'Dessert'), ('juice', 'Juice'), ('grill', 'Grill'), ('other', 'Other')], db_index=True, default='kitchen', max_length=20),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='code',
            field=models.CharField(blank=True, db_index=True, max_length=40),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='color_accent',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='image_url',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='kitchen_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_categories', to='restaurant.kitchenstation'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='mobile_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='restaurant.menucategory'),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='pos_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menucategory',
            name='tax_group',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allow_modifiers',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='allow_notes',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='availability_end',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='availability_start',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_delivery',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_dine_in',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='available_takeaway',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='base_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='coffee_attrs',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='kitchen_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='menu_items', to='restaurant.kitchenstation'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='mobile_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pos_visible',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='preparation_time_minutes',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='track_inventory',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='orderline',
            name='kitchen_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='restaurant.kitchenstation'),
        ),
        migrations.AddField(
            model_name='recipe',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='accepted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='barista_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_barista_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='priority',
            field=models.CharField(choices=[('normal', 'Normal'), ('high', 'High'), ('rush', 'Rush')], default='normal', max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='queue_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='ready_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='served_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='service_charge_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='restaurantorder',
            name='tip_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='diningtable',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('occupied', 'Occupied'), ('reserved', 'Reserved'), ('cleaning', 'Cleaning'), ('blocked', 'Blocked'), ('out_of_service', 'Out of service')], db_index=True, default='free', max_length=20),
        ),
        migrations.AddIndex(
            model_name='recipe',
            index=models.Index(fields=['tenant', 'menu_item', 'status'], name='idx_rest_recipe_active'),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_barista_profiles', to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='default_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='baristas', to='restaurant.kitchenstation'),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='baristaprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barista_profiles', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafeteriaprofile',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cafeteria_profiles', to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='cafeteriaprofile',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafeteriaprofile',
            name='default_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cafeteria_profiles', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='cafeteriaprofile',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cafeteriaprofile',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='cafeteriaprofile',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifier_group_links', to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='modifier_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_item_links', to='restaurant.modifiergroup'),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='menuitemmodifiergroup',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='menu_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='menuitemvariant',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderline',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='restaurant.menuitemvariant'),
        ),
        migrations.AddField(
            model_name='orderlinemodifier',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderlinemodifier',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='orderlinemodifier',
            name='modifier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_line_uses', to='restaurant.modifier'),
        ),
        migrations.AddField(
            model_name='orderlinemodifier',
            name='order_line',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='restaurant.orderline'),
        ),
        migrations.AddField(
            model_name='orderlinemodifier',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='orderlinemodifier',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='branch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_waste_records', to='settings_app.branch'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='employee_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_waste_records', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='ingredient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='restaurant.ingredient'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='menu_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waste_records', to='restaurant.menuitem'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='restaurant_waste_records', to='products.product'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='tenant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant'),
        ),
        migrations.AddField(
            model_name='wasterecord',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='baristaprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'branch', 'user'), name='uniq_rest_barista_tenant_branch_user'),
        ),
        migrations.AddConstraint(
            model_name='cafeteriaprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'branch'), name='uniq_cafeteria_profile_tenant_branch'),
        ),
        migrations.AddConstraint(
            model_name='menuitemmodifiergroup',
            constraint=models.UniqueConstraint(fields=('tenant', 'menu_item', 'modifier_group'), name='uniq_rest_item_modifier_group'),
        ),
        migrations.AddConstraint(
            model_name='menuitemvariant',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'menu_item', 'name'), name='uniq_rest_variant_tenant_item_name'),
        ),
        migrations.AddIndex(
            model_name='wasterecord',
            index=models.Index(fields=['tenant', 'branch', 'waste_type', 'waste_date'], name='idx_rest_waste_tenant'),
        ),
    ]
