# Generated by Django 5.2.17 on 2026-08-07 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0008_pt_billing'),
        ('sales', '0008_cashier_sessions_refunds'),
    ]

    operations = [
        migrations.AddField(
            model_name='classbooking',
            name='amount_charged',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gym_class_bookings', to='sales.invoice'),
        ),
        migrations.AddField(
            model_name='classbooking',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='gymclass',
            name='drop_in_price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
