# Generated by Django 5.2.17 on 2026-09-19 14:06

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0009_user_permission_revoke'),
        ('finance', '0009_business_units'),
        ('inventory', '0003_stock_transfers'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('settings_app', '0005_branch_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BranchAccessProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('description', models.TextField(blank=True)),
                ('grants_all_permissions', models.BooleanField(default=False, help_text="No narrowing: the holder's full global permission set applies in the branch. Explicit, so that a profile with an empty permission list means 'nothing' rather than accidentally meaning 'everything'.")),
                ('is_manager', models.BooleanField(default=False, help_text='Marks the holder as a manager of the branch (reporting/approval semantics).')),
                ('is_system', models.BooleanField(default=False, help_text='Seeded profile; kept in sync by bootstrap and not user-deletable.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, db_table='branch_access_profile_permissions', related_name='branch_access_profiles', to='authentication.permission')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'branch_access_profiles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('notes', models.TextField(blank=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cash_registers', to='settings_app.branch')),
                ('cash_account', models.ForeignKey(blank=True, help_text='Set by finance; never guessed during migration.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cash_registers', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cash_registers',
                'ordering': ['branch__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='StockLocation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('location_type', models.CharField(choices=[('STORAGE', 'Storage'), ('SHOP_FLOOR', 'Shop Floor'), ('RECEIVING', 'Receiving'), ('DISPATCH', 'Dispatch'), ('TRANSIT', 'In Transit'), ('DAMAGED', 'Damaged Goods'), ('RETURN', 'Returns'), ('OTHER', 'Other')], default='STORAGE', max_length=20)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('is_sellable', models.BooleanField(default=True, help_text='Stock here may be sold/picked (damaged and transit are not).')),
                ('is_default', models.BooleanField(default=False, help_text='Used when a movement does not name a location.')),
                ('sort_order', models.PositiveSmallIntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, help_text='Optional hierarchy (zone -> aisle -> shelf -> bin) for future per-bin stock.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='organization.stocklocation')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='inventory.warehouse')),
            ],
            options={
                'db_table': 'stock_locations',
                'ordering': ['warehouse__code', 'sort_order', 'code'],
            },
        ),
        migrations.CreateModel(
            name='PosTerminal',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(db_index=True, max_length=50)),
                ('name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('ARCHIVED', 'Archived')], default='ACTIVE', max_length=16)),
                ('device_identifier', models.CharField(blank=True, max_length=190)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pos_terminals', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('default_cash_register', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals', to='organization.cashregister')),
                ('default_warehouse', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals', to='inventory.warehouse')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('default_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pos_terminals', to='organization.stocklocation')),
            ],
            options={
                'db_table': 'pos_terminals',
                'ordering': ['branch__name', 'code'],
            },
        ),
        migrations.CreateModel(
            name='UserBranchAccess',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_default', models.BooleanField(default=False, help_text='Branch selected on login when no branch is requested.')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('ENDED', 'Ended')], default='ACTIVE', max_length=16)),
                ('starts_on', models.DateField(blank=True, null=True)),
                ('ends_on', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('access_profile', models.ForeignKey(blank=True, help_text="When empty the user's full global permission set applies in this branch.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_access', to='organization.branchaccessprofile')),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_access', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='branch_access', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_branch_access',
                'ordering': ['branch__name'],
            },
        ),
        migrations.AddConstraint(
            model_name='branchaccessprofile',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('tenant__isnull', False)), fields=('tenant', 'code'), name='branch_access_profile_tenant_code_unique'),
        ),
        migrations.AddIndex(
            model_name='cashregister',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='cash_regist_tenant__137e63_idx'),
        ),
        migrations.AddConstraint(
            model_name='cashregister',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'code'), name='cash_register_branch_code_unique'),
        ),
        migrations.AddIndex(
            model_name='stocklocation',
            index=models.Index(fields=['tenant', 'warehouse', 'status'], name='stock_locat_tenant__de8b55_idx'),
        ),
        migrations.AddConstraint(
            model_name='stocklocation',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('warehouse', 'code'), name='stock_location_warehouse_code_unique'),
        ),
        migrations.AddIndex(
            model_name='posterminal',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='pos_termina_tenant__5e87ca_idx'),
        ),
        migrations.AddConstraint(
            model_name='posterminal',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('branch', 'code'), name='pos_terminal_branch_code_unique'),
        ),
        migrations.AddIndex(
            model_name='userbranchaccess',
            index=models.Index(fields=['tenant', 'user', 'status'], name='user_branch_tenant__3404bd_idx'),
        ),
        migrations.AddIndex(
            model_name='userbranchaccess',
            index=models.Index(fields=['tenant', 'branch', 'status'], name='user_branch_tenant__c994aa_idx'),
        ),
        migrations.AddConstraint(
            model_name='userbranchaccess',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('user', 'branch'), name='user_branch_access_unique'),
        ),
    ]
