# Generated by Django 5.2.17 on 2026-09-20 15:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0001_initial'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('sales', '0010_backfill_default_terminals'),
        ('settings_app', '0005_branch_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProviderConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('provider_type', models.CharField(choices=[('MOCK', 'Mock (testing)')], max_length=20)),
                ('config', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='payment_providers', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_providers', to='integrations.integrationcredential')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('webhook_credential', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_webhook_providers', to='integrations.integrationcredential')),
            ],
            options={
                'db_table': 'payment_provider_configs',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PaymentIntent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('idempotency_key', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=4, max_digits=18)),
                ('currency', models.CharField(default='USD', max_length=3)),
                ('method', models.CharField(default='mobile', max_length=30)),
                ('status', models.CharField(choices=[('created', 'Created'), ('pending', 'Pending'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('expired', 'Expired')], db_index=True, default='created', max_length=12)),
                ('provider_reference', models.CharField(blank=True, max_length=190)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('failure_reason', models.CharField(blank=True, max_length=300)),
                ('settled_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_intents', to='sales.invoice')),
                ('payment', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_intent', to='sales.payment')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='intents', to='integrations.paymentproviderconfig')),
            ],
            options={
                'db_table': 'payment_intents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentWebhookEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_id', models.CharField(blank=True, max_length=190)),
                ('signature_valid', models.BooleanField(default=False)),
                ('raw_body', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('rejected', 'Rejected'), ('invalid', 'Invalid'), ('error', 'Error')], db_index=True, default='received', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=300)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='webhook_events', to='integrations.paymentintent')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='webhook_events', to='integrations.paymentproviderconfig')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_webhook_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReconciliationRecord',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('status_mismatch', 'Status mismatch'), ('amount_mismatch', 'Amount mismatch'), ('missing_payment', 'Succeeded without a payment'), ('missing_journal', 'Payment without a journal entry'), ('late_success', 'Success after expiry/failure'), ('unapplied_payment', 'Money taken but not applied')], max_length=24)),
                ('status', models.CharField(db_index=True, default='open', max_length=10)),
                ('provider_status', models.CharField(blank=True, max_length=20)),
                ('provider_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('ledger_status', models.CharField(blank=True, max_length=20)),
                ('ledger_amount', models.DecimalField(blank=True, decimal_places=4, max_digits=18, null=True)),
                ('detail', models.CharField(blank=True, max_length=300)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution_note', models.CharField(blank=True, max_length=300)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_reconciliations', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('intent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='integrations.paymentintent')),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='integrations.paymentproviderconfig')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_reconciliation_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(fields=('tenant', 'idempotency_key'), name='uniq_payment_intent_key'),
        ),
        migrations.AddConstraint(
            model_name='paymentintent',
            constraint=models.UniqueConstraint(condition=models.Q(('provider_reference', ''), _negated=True), fields=('provider', 'provider_reference'), name='uniq_payment_intent_provider_ref'),
        ),
        migrations.AddConstraint(
            model_name='paymentwebhookevent',
            constraint=models.UniqueConstraint(condition=models.Q(('event_id', ''), _negated=True), fields=('provider', 'event_id'), name='uniq_payment_webhook_event'),
        ),
        migrations.AddConstraint(
            model_name='reconciliationrecord',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'open')), fields=('intent', 'kind'), name='uniq_open_reconciliation'),
        ),
    ]
