from django.urls import path

from api.v1.platform.views import (
    PlatformBusinessTypesView,
    PlatformEntitlementsView,
    PlatformModulesCatalogView,
    PlatformMySubscriptionAlertView,
    PlatformPendingPaymentsView,
    PlatformPlansView,
    PlatformResolveHostView,
    PlatformShopGroupDetailView,
    PlatformShopGroupListCreateView,
    PlatformSlugCheckView,
    PlatformSubscriptionAlertsView,
    PlatformSubscriptionAssignView,
    PlatformSubscriptionConfirmPaymentView,
    PlatformSubscriptionDetailView,
    PlatformSubscriptionListCreateView,
    PlatformSubscriptionPaymentConfigView,
    PlatformSubscriptionPaymentStatusView,
    PlatformSubscriptionQrUploadView,
    PlatformSubscriptionRenewView,
    PlatformSubscriptionReportPaymentView,
    PlatformSubscriptionUpdateView,
    PlatformTenantDetailView,
    PlatformTenantDomainsView,
    PlatformTenantListCreateView,
    PlatformTenantModulesView,
    PlatformTenantSettingsView,
    PlatformTenantUsersView,
    PlatformBusinessPresetsView,
    PlatformDemoTenantActionView,
    PlatformDemoTenantListCreateView,
    PlatformWaafiPaymentCallbackView,
)

urlpatterns = [
    path("tenants/", PlatformTenantListCreateView.as_view(), name="platform-tenants"),
    path("tenants/<uuid:pk>/", PlatformTenantDetailView.as_view(), name="platform-tenant-detail"),
    path("tenants/<uuid:pk>/users/", PlatformTenantUsersView.as_view(), name="platform-tenant-users"),
    path(
        "tenants/<uuid:pk>/settings/",
        PlatformTenantSettingsView.as_view(),
        name="platform-tenant-settings",
    ),
    path(
        "tenants/<uuid:pk>/domains/",
        PlatformTenantDomainsView.as_view(),
        name="platform-tenant-domains",
    ),
    path(
        "tenants/<uuid:pk>/modules/",
        PlatformTenantModulesView.as_view(),
        name="platform-tenant-modules",
    ),
    path("tenants/<uuid:pk>/subscription/", PlatformSubscriptionUpdateView.as_view(), name="platform-subscription"),
    path("business-types/", PlatformBusinessTypesView.as_view(), name="platform-business-types"),
    path("business-presets/", PlatformBusinessPresetsView.as_view(), name="platform-business-presets"),
    path("demo-tenants/", PlatformDemoTenantListCreateView.as_view(), name="platform-demo-tenants"),
    path(
        "demo-tenants/<uuid:pk>/<str:action>/",
        PlatformDemoTenantActionView.as_view(),
        name="platform-demo-tenant-action",
    ),
    path("modules/", PlatformModulesCatalogView.as_view(), name="platform-modules"),
    path("slug-check/", PlatformSlugCheckView.as_view(), name="platform-slug-check"),
    path("resolve-host/", PlatformResolveHostView.as_view(), name="platform-resolve-host"),
    path("subscriptions/", PlatformSubscriptionListCreateView.as_view(), name="platform-subscriptions"),
    path("subscriptions/alerts/", PlatformSubscriptionAlertsView.as_view(), name="platform-subscription-alerts"),
    path("subscriptions/my-alert/", PlatformMySubscriptionAlertView.as_view(), name="platform-my-subscription-alert"),
    path("entitlements/", PlatformEntitlementsView.as_view(), name="platform-entitlements"),
    path(
        "subscriptions/payment-config/",
        PlatformSubscriptionPaymentConfigView.as_view(),
        name="platform-subscription-payment-config",
    ),
    path(
        "subscriptions/payment-config/upload-qr/",
        PlatformSubscriptionQrUploadView.as_view(),
        name="platform-subscription-payment-qr",
    ),
    path(
        "subscriptions/pending-payments/",
        PlatformPendingPaymentsView.as_view(),
        name="platform-pending-payments",
    ),
    path("subscriptions/<uuid:pk>/", PlatformSubscriptionDetailView.as_view(), name="platform-subscription-detail"),
    path("subscriptions/<uuid:pk>/assign/", PlatformSubscriptionAssignView.as_view(), name="platform-subscription-assign"),
    path("subscriptions/<uuid:pk>/renew/", PlatformSubscriptionRenewView.as_view(), name="platform-subscription-renew"),
    path(
        "subscriptions/<uuid:pk>/report-payment/",
        PlatformSubscriptionReportPaymentView.as_view(),
        name="platform-subscription-report-payment",
    ),
    path(
        "subscriptions/<uuid:pk>/payment-status/",
        PlatformSubscriptionPaymentStatusView.as_view(),
        name="platform-subscription-payment-status",
    ),
    path(
        "payments/<uuid:pk>/confirm/",
        PlatformSubscriptionConfirmPaymentView.as_view(),
        name="platform-payment-confirm",
    ),
    path(
        "payments/waafi-callback/",
        PlatformWaafiPaymentCallbackView.as_view(),
        name="platform-waafi-callback",
    ),
    path("shop-groups/", PlatformShopGroupListCreateView.as_view(), name="platform-shop-groups"),
    path("shop-groups/<uuid:pk>/", PlatformShopGroupDetailView.as_view(), name="platform-shop-group-detail"),
    path("plans/", PlatformPlansView.as_view(), name="platform-plans"),
]
