# Generated by Django 5.2.17 on 2026-08-07 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionline',
            name='quantity_dispensed',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
    ]
