def serialize_wbs_node(row) -> dict:
    return {
        "id": str(row.id),
        "project_id": str(row.project_id),
        "project_code": row.project.project_code if row.project_id else "",
        "project_name": row.project.name if row.project_id else "",
        "parent_id": str(row.parent_id) if row.parent_id else None,
        "parent_code": row.parent.code if row.parent_id else "",
        "parent_name": row.parent.name if row.parent_id else "",
        "code": row.code,
        "name": row.name,
        "node_type": row.node_type,
        "description": row.description or "",
        "sort_order": row.sort_order,
        "level": row.level,
        "planned_start": row.planned_start.isoformat() if row.planned_start else None,
        "planned_end": row.planned_end.isoformat() if row.planned_end else None,
        "actual_start": row.actual_start.isoformat() if row.actual_start else None,
        "actual_end": row.actual_end.isoformat() if row.actual_end else None,
        "status": row.status,
        "progress_percent": float(row.progress_percent or 0),
        "estimated_hours": float(row.estimated_hours or 0),
        "estimated_cost": float(row.estimated_cost or 0),
        "notes": row.notes or "",
        "created_at": row.created_at.isoformat() if row.created_at else None,
        "updated_at": row.updated_at.isoformat() if row.updated_at else None,
    }
