# Generated by Django 5.2.17 on 2026-08-07 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_pos_search_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(db_index=True, default=False, help_text='When pharmacy module is enabled, POS requires an active Rx covering this product.'),
        ),
    ]
