# Generated by Django 5.2.17 on 2026-09-20 05:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_branch_transfer_workflow'),
        ('organization', '0004_backfill_user_branch_access'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('sales', '0008_cashier_sessions_refunds'),
        ('settings_app', '0005_branch_profile_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cashiersession',
            name='cash_in',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='cash_out',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=18),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='organization.stocklocation'),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='register',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='organization.cashregister'),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sessions', to='organization.posterminal'),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='variance_approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='variance_approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_cash_variances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='variance_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='cashiersession',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pos_sessions', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terminal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='organization.posterminal'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_invoices', to='inventory.warehouse'),
        ),
        migrations.AddConstraint(
            model_name='cashiersession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('status', 'open'), ('terminal__isnull', False)), fields=('terminal',), name='uniq_open_session_per_terminal'),
        ),
        migrations.AddConstraint(
            model_name='cashiersession',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('register__isnull', False), ('status', 'open')), fields=('register',), name='uniq_open_session_per_register'),
        ),
    ]
