# Generated by Django 5.2.17 on 2026-09-21 18:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_backfill_journalline_branch'),
        ('platform', '0018_alter_agreementacceptance_created_by_and_more'),
        ('sales', '0011_phase6_billing'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingcredit',
            name='reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='billingcredit',
            name='reversal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingcredit',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='billingrefund',
            name='reversal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='billingrefund',
            name='reversal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billingrefund',
            name='reversal_reason',
            field=models.TextField(blank=True),
        ),
    ]
