# Generated by Django 5.2.17 on 2026-08-07 15:14

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0002_tenant_isolation'),
        ('platform', '0016_demo_tenant_fields'),
        ('property_management', '0001_initial'),
        ('sales', '0008_cashier_sessions_refunds'),
        ('settings_app', '0003_tenant_isolation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeLease',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('lease_number', models.CharField(db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('expired', 'Expired'), ('terminated', 'Terminated'), ('renewed', 'Renewed')], db_index=True, default='draft', max_length=20)),
                ('start_date', models.DateField(db_index=True)),
                ('end_date', models.DateField(blank=True, db_index=True, null=True)),
                ('rent_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('service_charge', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('deposit_held', models.BooleanField(default=False)),
                ('parking_slots', models.PositiveSmallIntegerField(default=0)),
                ('furnished', models.BooleanField(default=False)),
                ('internet_included', models.BooleanField(default=False)),
                ('electricity_included', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('terminated_at', models.DateTimeField(blank=True, null=True)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_leases', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='office_leases', to='property_management.propertyunit')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'office_leases',
                'ordering': ['-start_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeLeaseCharge',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('charge_type', models.CharField(choices=[('rent', 'Rent'), ('service', 'Service charge'), ('deposit', 'Security deposit'), ('other', 'Other')], db_index=True, default='rent', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('invoiced', 'Invoiced'), ('paid', 'Paid'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('period_start', models.DateField(blank=True, null=True)),
                ('period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, db_index=True, null=True)),
                ('posted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('branch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='office_lease_charges', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_lease_charges', to='sales.invoice')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='charges', to='office_rental.officelease')),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'office_lease_charges',
                'ordering': ['-posted_at', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OfficeTenant',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('company_name', models.CharField(db_index=True, max_length=200)),
                ('registration_number', models.CharField(blank=True, max_length=80)),
                ('contact_name', models.CharField(blank=True, max_length=200)),
                ('phone', models.CharField(blank=True, db_index=True, max_length=40)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='office_tenants', to='settings_app.branch')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='office_tenants', to='customers.customer')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_deleted', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='%(app_label)s_%(class)s_set', to='platform.tenant')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'office_tenants',
                'ordering': ['company_name'],
            },
        ),
        migrations.AddField(
            model_name='officelease',
            name='office_tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='leases', to='office_rental.officetenant'),
        ),
        migrations.AddIndex(
            model_name='officetenant',
            index=models.Index(fields=['tenant', 'is_active', 'company_name'], name='idx_office_tenant_name'),
        ),
        migrations.AddIndex(
            model_name='officelease',
            index=models.Index(fields=['tenant', 'status', 'start_date'], name='idx_office_lease_tenant'),
        ),
    ]
