export const resources: Record<string, {title: string; permission: string; columns: string[]; readonly?: boolean}> = {
 applications:{title:'Applications',permission:'admission',columns:['number','applicant_name','school_class_name','branch_name','academic_year_name','application_date','missing_documents','status']},
 applicants:{title:'Applicants',permission:'applicant',columns:['name','number','branch_name','date_of_birth','phone','status']},
 students:{title:'Students',permission:'student',columns:['name','number','branch_name','current_class','current_section','primary_guardian_name','guardian_phone','status','admission_date']},
 families:{title:'Families',permission:'family',columns:['name','code','primary_guardian_id','phone','student_count','branch_name','status']},
 guardians:{title:'Guardians',permission:'guardian',columns:['name','number','phone','email','student_count','portal_eligible','status']},
 assessments:{title:'Assessments',permission:'assessment',columns:['application_id','assessment_type','date','start_time','score','result','status']},
 interviews:{title:'Interviews',permission:'interview',columns:['application_id','date','start_time','location','recommendation','status']},
 decisions:{title:'Decisions',permission:'decision',columns:['application_id','decision','decision_date','reason'],readonly:true},
 enrollments:{title:'Enrollments',permission:'enrollment',columns:['student_name','academic_year_name','branch_name','school_class_name','section_name','roll_number','start_date','end_date','status']},
 transitions:{title:'Student history',permission:'student_transition',columns:['student_name','outcome','effective_date','reason'],readonly:true},
 'document-types':{title:'Document requirements',permission:'document_type',columns:['name','code','required','branch_name','expiry_required','status']},
 'admission-policies':{title:'Admission policies',permission:'admission_policy',columns:['branch_name','require_guardian','require_family','capacity_policy','student_prefix']},
 'relationship-types':{title:'Relationship types',permission:'relationship_type',columns:['name','code','status']},
 'student-guardians':{title:'Student guardians',permission:'student_guardian',columns:['student_name','guardian_name','relationship_name','is_primary','phone','status']},
 'applicant-guardians':{title:'Applicant guardians',permission:'applicant_guardian',columns:['applicant_name','guardian_name','relationship_name','is_primary','status']},
 'student-documents':{title:'Student documents',permission:'student_document',columns:['student_name','document_type_name','category','expiry_date','verification_status']},
 'applicant-documents':{title:'Application documents',permission:'admission_document',columns:['application_id','document_type_name','expiry_date','verification_status']},
 'emergency-contacts':{title:'Emergency contacts',permission:'emergency_contact',columns:['student_name','name','relationship','phone','priority']},
 notes:{title:'Student notes',permission:'student_note',columns:['student_name','title','category','created_at']},
 employees:{title:'Employees',permission:'employee',columns:['name','code','job_title','employment_type','branch_name','status']},
 'staff-profiles':{title:'Teaching staff',permission:'staff_profile',columns:['employee_name','staff_type','specialization','max_weekly_periods','branch_name','status']},
 'teacher-assignments':{title:'Teacher assignments',permission:'teacher_assignment',columns:['staff_name','role','school_class_name','section_name','subject_offering_name','academic_year_name','start_date','end_date','status']},
 classrooms:{title:'Rooms',permission:'classroom',columns:['name','code','room_type','capacity','branch_name','status']},
 periods:{title:'Timetable periods',permission:'period',columns:['name','code','start_time','end_time','is_break','branch_name','status']},
 'timetable-versions':{title:'Timetables',permission:'timetable',columns:['name','branch_name','academic_year_name','effective_from','effective_to','status','published_at']},
 'timetable-entries':{title:'Timetable lessons',permission:'timetable_entry',columns:['weekday','period_name','school_class_name','section_name','subject_offering_name','staff_name','classroom_name','status']},
 'attendance-sessions':{title:'Attendance sessions',permission:'attendance',readonly:true,columns:['date','mode','school_class_name','section_name','period_name','record_count','absent_count','status']},
 'attendance-records':{title:'Attendance records',permission:'attendance_record',readonly:true,columns:['student_name','status','remarks','session_name','updated_at']},
 'attendance-corrections':{title:'Attendance corrections',permission:'attendance_correction',readonly:true,columns:['record_name','old_status','new_status','reason','status','decided_at']},
 "grade-schemes":{title:"Grade schemes",permission:"grade_scheme",columns:["name", "code", "branch_name"]},
 "grade-bands":{title:"Grade bands",permission:"grade_band",columns:["scheme_name", "label", "minimum", "maximum", "passing"]},
 "assignments":{title:"Assignments",permission:"assignment",columns:["title", "subject_offering_name", "assigned_date", "due_date", "status"]},
 "submissions":{title:"Submissions",permission:"submission",columns:["assignment_name", "enrollment_name", "submitted_at", "score", "status"]},
 "exams":{title:"Exams and results",permission:"exam",columns:["name", "academic_year_name", "school_class_name", "section_name", "status", "revision"]},
 "academic-assessments":{title:"Academic assessments",permission:"academic_assessment",columns:["name", "exam_name", "subject_offering_name", "date", "maximum_score", "weight"]},
 "exam-schedules":{title:"Exam schedules",permission:"exam_schedule",columns:["assessment_name", "classroom_name", "staff_name", "start_time", "end_time"]},
 "marks":{title:"Marks",permission:"mark",columns:["assessment_name", "enrollment_name", "score", "outcome"],readonly:true},
 "result-publications":{title:"Published results",permission:"result_publication",columns:["exam_name", "version", "created_at"],readonly:true},
 "report-cards":{title:"Report cards",permission:"report_card",columns:["student_name", "publication_name", "created_at"],readonly:true},
 "promotion-batches":{title:"Promotion batches",permission:"promotion",columns:["publication_name", "effective_date", "status"],readonly:true},
 "promotion-items":{title:"Promotion history",permission:"promotion_item",columns:["enrollment_name", "target_class_name", "outcome"],readonly:true},
 "fee-settings":{title:"Finance mappings",permission:"fee_settings",columns:["branch_name", "receivable_mapping_key", "advance_mapping_key", "credit_mapping_key"]},
 "fee-categories":{title:"Fee categories",permission:"fee_category",columns:["name", "code", "revenue_mapping_key", "recognition", "status"]},
 "fee-structures":{title:"Fee structures",permission:"fee_structure",columns:["name", "academic_year_name", "school_class_name", "status"]},
 "fee-lines":{title:"Fee structure lines",permission:"fee_line",columns:["name", "period_key", "amount", "due_date"]},
 "fee-discounts":{title:"Scholarships and discounts",permission:"fee_discount",columns:["student_name", "fee_name", "kind", "value", "reason", "status"]},
 "fee-batches":{title:"Fee generation batches",permission:"fee_batch",columns:["name", "issue_date", "status"],readonly:true},
 "fee-assignments":{title:"Assigned fees",permission:"fee_assignment",columns:["student_name", "fee_name", "gross_amount", "discount_amount", "amount"],readonly:true},
 "fee-invoices":{title:"School invoice links",permission:"fee_invoice",columns:["number", "student_name", "customer_name", "total_amount", "balance", "status"],readonly:true},
 "billing-invoices":{title:"Fee invoices",permission:"fee_invoice",columns:["name", "customer_name", "issue_date", "due_date", "total_amount", "amount_paid", "balance", "status"],readonly:true},
 "billing-methods":{title:"Payment methods",permission:"billing_method",columns:["name", "code", "account_mapping_key", "is_active"]},
 "billing-customers":{title:"Billing customers",permission:"billing_customer",columns:["name", "customer_code", "phone", "branch_name"]},
 "billing-receipts":{title:"Receipts and advances",permission:"billing_receipt",columns:["name", "customer_name", "amount", "available", "received_date", "status"],readonly:true},
 "billing-allocations":{title:"Receipt allocations",permission:"billing_allocation",columns:["invoice_number", "amount", "date", "reason", "reversal_date"],readonly:true},
 "billing-credits":{title:"Credit notes",permission:"billing_credit",columns:["invoice_number", "amount", "date", "reason"],readonly:true},
 "billing-refunds":{title:"Refunds",permission:"billing_refund",columns:["amount", "date", "reason"],readonly:true},
 "billing-lines":{title:"Issued fee lines",permission:"fee_invoice",columns:["name", "gross_amount", "discount_amount", "amount"],readonly:true},
 "billing-cost-centers":{title:"Cost centers",permission:"fee_settings",columns:["name", "code", "is_active"],readonly:true},
 "billing-business-units":{title:"Business units",permission:"fee_settings",columns:["name", "code", "is_active"],readonly:true},
};
export const path = (resource: string) => `/school/sis/${resource}`;
export const label = (key: string) => key.replace(/_id$|_name$/g,'').replace(/_/g,' ').replace(/^./,c=>c.toUpperCase());
export const text = (value: unknown): string => value === null || value === undefined || value === '' ? '—' : typeof value === 'boolean' ? value ? 'Yes':'No' : typeof value === 'object' ? JSON.stringify(value) : String(value).replace(/_/g,' ');
